"""add base models

Revision ID: 8e3593ef15c5
Revises: 70550bfd960f
Create Date: 2026-04-04 09:04:10.232568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3593ef15c5'
down_revision: Union[str, Sequence[str], None] = '70550bfd960f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_log_action'), 'operation_log', ['action'], unique=False)
    op.create_index(op.f('ix_operation_log_id'), 'operation_log', ['id'], unique=False)
    op.create_index(op.f('ix_operation_log_project_id'), 'operation_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_operation_log_resource_id'), 'operation_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_operation_log_resource_type'), 'operation_log', ['resource_type'], unique=False)
    op.create_table('pipeline',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_id'), 'pipeline', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_name'), 'pipeline', ['name'], unique=False)
    op.create_index(op.f('ix_pipeline_project_id'), 'pipeline', ['project_id'], unique=False)
    op.create_table('setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_id'), 'setting', ['id'], unique=False)
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=False)
    op.create_index(op.f('ix_setting_project_id'), 'setting', ['project_id'], unique=False)
    op.create_table('template',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=False)
    op.create_index(op.f('ix_template_project_id'), 'template', ['project_id'], unique=False)
    op.create_index(op.f('ix_template_type'), 'template', ['type'], unique=False)
    op.create_table('run',
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('error_info', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dataset_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_id'), 'run', ['id'], unique=False)
    op.create_index(op.f('ix_run_pipeline_id'), 'run', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_run_project_id'), 'run', ['project_id'], unique=False)
    op.create_index(op.f('ix_run_snapshot_id'), 'run', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_run_status'), 'run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_status'), table_name='run')
    op.drop_index(op.f('ix_run_snapshot_id'), table_name='run')
    op.drop_index(op.f('ix_run_project_id'), table_name='run')
    op.drop_index(op.f('ix_run_pipeline_id'), table_name='run')
    op.drop_index(op.f('ix_run_id'), table_name='run')
    op.drop_table('run')
    op.drop_index(op.f('ix_template_type'), table_name='template')
    op.drop_index(op.f('ix_template_project_id'), table_name='template')
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_setting_project_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_index(op.f('ix_setting_id'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_pipeline_project_id'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_name'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_id'), table_name='pipeline')
    op.drop_table('pipeline')
    op.drop_index(op.f('ix_operation_log_resource_type'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_resource_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_project_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_id'), table_name='operation_log')
    op.drop_index(op.f('ix_operation_log_action'), table_name='operation_log')
    op.drop_table('operation_log')
    # ### end Alembic commands ###
